# .pre-commit-config.yaml
repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: [
                '--exclude-files', '.yarn',
                '--exclude-files', 'client',
                '--exclude-files', 'test',
                '--exclude-files', 'logs/*',
                '--exclude-files', 'src/locales/*',
                '--exclude-files', '.env',
                '--exclude-secrets', 'cat .env \| fly secrets import'
              ]
