name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRETS_JSON: ${{ toJson(secrets) }} # convert all secrets to JSON string

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable  
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Export all secrets dynamically
        run: |
          echo "$SECRETS_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Run Tests
        run: yarn test